name: Dungeon-Dungeon-And-More-Dungeons
version: '${project.version}'
main: kz.blazingfast.minecraft.dungeondungeonandmoredungeons.DungeonDungeonAndMoreDungeons
api-version: 1.19

commands:
  register:
    aliases:
      - reg

  login:
    aliases:
      - l

  logout:
    aliases:
      - lout
  event:
    description: event command

  subscribe:
    aliases:
      - sub

  unsubscribe:
    aliases:
      - unsub

  shop:
